apiVersion: v1
kind: Pod
metadata:
  name: POD_NAME
spec:
  automountServiceAccountToken: false
  hostname: POD_NAME
  nodeName: NODE_NAME
  hostNetwork: true
  containers:
  - name: client
    image: alpine:3.13
    command: ["/bin/sh"]
    args: ["-c","while true; do date; echo 'hello'; sleep 10; done"]
